import test from 'node:test';
import assert from 'node:assert/strict';
import { database,record,seed,NOW } from './helpers.mjs';
import worker,{wakeStage} from '../../platform/findpitches-v3/worker.mjs';
import { verifyStructuredControl } from '../../platform/findpitches-v3/control.mjs';
import { sql,ingestRecords } from '../../platform/findpitches-v3/store.mjs';
import { drainPipeline } from '../../platform/findpitches-v3/pipeline.mjs';
const TOKEN='local-test-token-with-at-least-24-characters';
const request=(path,{method='GET',body,token=TOKEN}={})=>new Request('https://v3.example'+path,{method,headers:{authorization:'Bearer '+token,'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});
test('Worker APIs enforce authentication, role ownership, payload limits and hard publication disablement',async t=>{
  const db=database(t),env={FINDPITCHES_V3_DB:db,V3_ROLE:'ingest',V3_INGEST_TOKEN:TOKEN,V3_OPERATOR_TOKEN:TOKEN,PUBLICATION_ENABLED:'true'};
  assert.equal((await worker.fetch(request('/health'),env)).status,200);
  assert.equal((await worker.fetch(request('/imports',{method:'POST',body:{records:[record()]},token:'invalid'}),env)).status,401);
  assert.equal((await worker.fetch(request('/imports',{method:'POST',body:{records:[record()],environment:'test'}}),env)).status,202);
  assert.equal((await worker.fetch(request('/imports',{method:'POST',body:{records:[record()]} }),{...env,V3_ROLE:'api'})).status,404);
  assert.equal((await worker.fetch(request('/v1/opportunities'),env)).status,403);
  assert.equal((await worker.fetch(request('/shadow',{token:'invalid'}),{...env,V3_ROLE:'api'})).status,401);
  assert.equal((await worker.fetch(request('/imports',{method:'POST',body:{records:[],padding:'x'.repeat(1048576)}}),env)).status,413);
  const response=await worker.fetch(request('/status',{token:''}),env),status=await response.json();assert.equal(status.mode,'shadow');assert.equal(status.publication_enabled,false);assert.equal(status.customer_rows,0);assert.equal(status.publication_rows,0);
  assert.ok(status.jobs);assert.ok(status.throughput);assert.ok(status.stale_leases===0);
});
test('stage queue deliveries are idempotent and wrong-stage messages fail transport validation',async t=>{
  const db=database(t);await seed(db);let acks=0,retries=0;
  const messages=[{body:{stage:'readiness',job_id:'unknown'},ack:()=>acks++,retry:()=>retries++},{body:{stage:'reconcile',job_id:'wrong'},ack:()=>acks++,retry:()=>retries++}];
  await worker.queue({messages},{FINDPITCHES_V3_DB:db,V3_ROLE:'readiness'});assert.equal(acks,1);assert.equal(retries,1);
});
test('operator corroboration reselection upgrades retained stronger facts without changing values and refuses unrelated or differing facts',async t=>{
  const db=database(t);await sql(db,"INSERT INTO quality_gates VALUES ('structured-100-preservation',100,0,'{}','gate',?)",NOW).run();
  const weak=await seed(db,record(),{producer:'city-search',environment:'shadow'});
  const strong=await ingestRecords(db,[record()],{environment:'shadow',now:NOW}),id=strong.record_ids[0];
  await sql(db,'INSERT INTO entity_records VALUES (?,?)',id,weak.entity.id).run();
  await sql(db,'INSERT INTO entity_facts SELECT ?,id FROM source_facts WHERE record_id=?',weak.entity.id,id).run();
  const env={FINDPITCHES_V3_DB:db,V3_ROLE:'enrichment',V3_OPERATOR_TOKEN:TOKEN};
  const body={entity_id:weak.entity.id,fact_ids:[id+':event_name']};
  assert.equal((await worker.fetch(request('/corroboration/reselect',{method:'POST',body,token:'invalid'}),env)).status,401);
  const response=await worker.fetch(request('/corroboration/reselect',{method:'POST',body}),env);assert.equal(response.status,200);
  assert.equal((await response.json()).source_value_mutations,0);
  const selected=await sql(db,"SELECT authority,value_json FROM selected_facts WHERE entity_id=? AND field_name='event_name'",weak.entity.id).first();
  assert.equal(selected.authority,100);assert.equal(JSON.parse(selected.value_json),record().event_name);
  const different=await ingestRecords(db,[record({opportunity_id:'different-value',event_name:'Different source title'})],{environment:'shadow',now:NOW});
  const otherId=different.record_ids[0];
  assert.equal((await worker.fetch(request('/corroboration/reselect',{method:'POST',body:{...body,fact_ids:[otherId+':event_name']}}),env)).status,400);
  await sql(db,'INSERT INTO entity_records VALUES (?,?)',otherId,weak.entity.id).run();await sql(db,'INSERT INTO entity_facts SELECT ?,id FROM source_facts WHERE record_id=?',weak.entity.id,otherId).run();
  assert.equal((await worker.fetch(request('/corroboration/reselect',{method:'POST',body:{...body,fact_ids:[otherId+':event_name']}}),env)).status,400);
});
test('concurrent transport wake-ups coalesce each durable job and completed duplicate pointers do not fan out',async t=>{
  const db=database(t),sent=[];
  await ingestRecords(db,[record()],{environment:'shadow',now:NOW});
  const env={FINDPITCHES_V3_DB:db,V3_ROLE:'reconcile',NEXT_QUEUE:{sendBatch:async messages=>sent.push(...messages)}};
  await Promise.all(Array.from({length:5},()=>wakeStage(env,'reconcile')));
  assert.equal(sent.length,1);assert.equal((await sql(db,'SELECT COUNT(*) AS count FROM queue_dispatches').first()).count,1);
  await sql(db,"UPDATE jobs SET status='complete' WHERE id=?",sent[0].body.job_id).run();
  let acks=0;await worker.queue({messages:[{body:sent[0].body,ack:()=>acks++,retry:()=>assert.fail('completed pointer should be acknowledged')}]},env);
  assert.equal(acks,1);assert.equal(sent.length,1);
});
test('reconciliation ticks process one record and cron fans pending work into the existing self queue',async t=>{
  const db=database(t),sent=[],pending=[];
  const records=Array.from({length:3},(_,i)=>record({opportunity_id:'tick-'+i,application_url:`https://www.eventeny.com/events/vendor/?id=${90000+i}`,canonical_url:`https://www.eventeny.com/events/vendor/?id=${90000+i}`}));
  await ingestRecords(db,records,{environment:'shadow',now:NOW});
  const env={FINDPITCHES_V3_DB:db,V3_ROLE:'reconcile',V3_OPERATOR_TOKEN:TOKEN,SELF_QUEUE:{sendBatch:async messages=>sent.push(...messages)}};
  const response=await worker.fetch(request('/tick',{method:'POST',body:{limit:25}}),env);
  assert.equal(response.status,200);
  const result=await response.json();
  assert.equal(result.results.length,1);
  assert.equal(result.results[0].phase,'complete');
  assert.equal((await sql(db,"SELECT COUNT(*) AS n FROM jobs WHERE stage='reconcile' AND status='ready'").first()).n,2);
  await worker.scheduled({},env,{waitUntil:p=>pending.push(p)});
  await Promise.all(pending);
  assert.equal(sent.length,2);
  assert.ok(sent.every(message=>message.body.stage==='reconcile'));
  assert.equal(new Set(sent.map(message=>message.body.job_id)).size,2);
  assert.equal((await sql(db,"SELECT COUNT(*) AS n FROM jobs WHERE stage='reconcile' AND status='complete'").first()).n,2);
  assert.equal((await sql(db,"SELECT COUNT(*) AS n FROM jobs WHERE stage='reconcile' AND status='ready'").first()).n,1);
});
test('preservation gate cannot be declared from unprocessed records or client counts',async t=>{
  const db=database(t);
  await assert.rejects(verifyStructuredControl(db,[record()],['invented']),/exactly_100/);
});
test('producer recheck acknowledgment requires newer linked evidence and the exact request timestamp',async t=>{
  const db=database(t),{entity}=await seed(db,record(),{environment:'shadow'});
  const requested_at='2026-10-07T12:00:00.000Z',env={FINDPITCHES_V3_DB:db,V3_ROLE:'ingest',V3_INGEST_TOKEN:TOKEN};
  await sql(db,"INSERT INTO recheck_requests VALUES (?,?,'watch_recheck_due')",entity.id,requested_at).run();
  const ack=async time=>(await worker.fetch(request('/rechecks/ack',{method:'POST',body:{entity_id:entity.id,requested_at:time}}),env)).json();
  assert.equal((await ack(requested_at)).acknowledged,false);
  await ingestRecords(db,[record({last_checked:'2026-10-08T12:00:00.000Z'})],{environment:'shadow',now:'2026-10-08T12:00:00.000Z'});await drainPipeline(db,{now:'2026-10-08T12:00:00.000Z'});
  assert.equal((await ack('2026-10-06T12:00:00.000Z')).acknowledged,false);
  assert.equal((await ack(requested_at)).acknowledged,true);
});
test('canary API rejects undelegated runs and schedules one fixed query without enabling the bulk route',async t=>{
  const db=database(t),run_id='canary_12345678-1234-1234-1234-123456789abc';
  const env={FINDPITCHES_V3_DB:db,V3_ROLE:'acquisition',V3_OPERATOR_TOKEN:TOKEN,V3_CITY_ENABLED:'false',V3_DAILY_QUERY_LIMIT:'0'};
  const post=path=>worker.fetch(request(path,{method:'POST',body:{run_id,query_limit:4,city:'not-approved'}}),env);
  assert.equal((await post('/acquisition/canary')).status,400);
  env.V3_CANARY_RUN_ID=run_id;env.V3_CANARY_EXPIRES_AT=new Date(Date.now()+60000).toISOString();
  assert.equal((await post('/acquisition/canary')).status,202);
  const job=await sql(db,"SELECT payload_json FROM jobs WHERE stage='acquisition'").first(),payload=JSON.parse(job.payload_json);
  assert.equal(payload.query_limit,1);assert.equal(payload.city,'austin-tx');assert.equal(payload.canary,true);
  assert.equal((await post('/acquisition')).status,400);
});
