// GENERATED by scripts/build-seo-module.mjs from public/assets/js/{routes.js,seo/seo-config.js,seo/seo-core.js}. Do not edit.
// Pure functions, no DOM and no network: safe in Cloudflare Workers, Node or any server renderer.
const window = { FP: {} };
// ---- public/assets/js/routes.js
/*
 * FindPitches routing helpers (frontend concern, no data).
 *
 * Canonical market identifiers are ALWAYS the uppercase market codes used by the backend:
 *   GB, US, CA, AU, IE, NZ, SG, HK
 * Customer-facing URLs use friendly SEO slugs (GB → /uk/). Translation happens only here.
 *
 * The offline draft is a set of static files, so "clean" paths such as /uk/stall-holders-wanted/kent/
 * are opened as  seo.html?path=/uk/stall-holders-wanted/kent/  — the canonical (clean) URL is still
 * what the SEO layer emits in <link rel=canonical>, sitemaps and hreflang.
 */
(function () {
  const FP = (window.FP = window.FP || {});
  const MARKET_ORDER = ['GB', 'US', 'CA', 'AU', 'IE', 'NZ', 'SG', 'HK'];
  const SLUG = { GB: 'uk', US: 'us', CA: 'ca', AU: 'au', IE: 'ie', NZ: 'nz', SG: 'sg', HK: 'hk' };
  const FROM_SLUG = Object.fromEntries(Object.entries(SLUG).map(([k, v]) => [v, k]));
  const SITE = 'https://findpitches.com';

  const routes = {
    SITE, MARKET_ORDER,
    slugOf: code => SLUG[String(code || '').toUpperCase()] || null,
    // Accepts a route slug ('uk'), a canonical code ('GB') or legacy lowercase codes; returns canonical code or null.
    marketOf(v) {
      if (!v) return null; const s = String(v).trim();
      if (SLUG[s.toUpperCase()]) return s.toUpperCase();
      return FROM_SLUG[s.toLowerCase()] || null;
    },
    /* Canonical (production) paths */
    marketPath: m => `/${SLUG[m]}/`,
    opportunityPath: (m, id) => `/${SLUG[m]}/opportunity/${encodeURIComponent(id)}/`,
    finderPath: m => `/${SLUG[m]}/find-pitches/`,
    abs: path => SITE + path,
    /* Draft (static file) links */
    draft: {
      finder: (m, params) => 'finder.html?' + new URLSearchParams(Object.assign({ cc: SLUG[m] }, params || {})).toString(),
      opportunity: id => 'opportunity.html?id=' + encodeURIComponent(id),
      seo: path => 'seo.html?path=' + encodeURIComponent(path)
    }
  };
  FP.routes = routes;
})();

// ---- public/assets/js/seo/seo-config.js
/*
 * FindPitches SEO landing-page registry (offline draft).
 *
 * One registry drives every landing page. A page is a combination of:
 *   market (canonical code)  +  optional intent  +  optional region
 * e.g.  GB + stall-holders-wanted + kent  →  /uk/stall-holders-wanted/kent/
 *
 * Intents are market-neutral KEYS with localised slugs, labels and wording per market,
 * so "Stall holders wanted" (GB) and "Vendors wanted" (US) are the same intent and are
 * linked with hreflang. Filters map an intent onto FP.api search parameters.
 *
 * In production this registry should be owned server-side (it drives server-rendered pages,
 * sitemaps and redirects). The draft keeps it here so it can be reviewed and edited easily.
 */
(function () {
  const FP = (window.FP = window.FP || {});

  const INTENTS = [
    // generic: true → no filters, so intent × region would duplicate the region page. Those URLs 301 to the region page.
    { key: 'traders-wanted', filters: {}, generic: true,
      keywords: { GB: ['stall holders wanted', 'stallholders wanted', 'market traders wanted', 'traders wanted'], US: ['vendors wanted', 'vendor opportunities', 'looking for vendors'] },
      slugs: { GB: 'stall-holders-wanted', US: 'vendors-wanted', CA: 'vendors-wanted', AU: 'stallholders-wanted', IE: 'traders-wanted', NZ: 'stallholders-wanted', SG: 'vendors-wanted', HK: 'vendors-wanted' },
      labels: { GB: 'Stall holders wanted', US: 'Vendors wanted', CA: 'Vendors wanted', AU: 'Stallholders wanted', IE: 'Traders wanted', NZ: 'Stallholders wanted', SG: 'Vendors wanted', HK: 'Vendors wanted' },
      blurb: 'Every checked market, fair, festival, show and event looking for traders.' },
    { key: 'festivals', filters: { types: ['festival', 'food_festival', 'show'] },
      // festival-vendors-wanted is MERGED here (301). Its wording is kept as keyword metadata, not a second page.
      keywords: { GB: ['festival trader applications', 'festival vendors wanted', 'festival traders wanted', 'festival pitches'], US: ['festival vendor applications', 'festival vendors wanted', 'fair vendor applications'] },
      slugs: { GB: 'festival-trader-applications', US: 'festival-vendor-applications', CA: 'festival-vendor-applications', AU: 'festival-stallholder-applications', IE: 'festival-trader-applications', NZ: 'festival-stallholder-applications', SG: 'festival-vendor-applications', HK: 'festival-vendor-applications' },
      labels: { GB: 'Festival trader applications', US: 'Festival vendor applications', CA: 'Festival vendor applications', AU: 'Festival stallholder applications', IE: 'Festival trader applications', NZ: 'Festival stallholder applications', SG: 'Festival vendor applications', HK: 'Festival vendor applications' },
      blurb: 'Food festivals, music and arts festivals, county shows and fairs taking applications.' },
    { key: 'food', filters: { sells: 'food' },
      // food-truck-pitches is MERGED here (301). Its wording is kept as keyword metadata, not a second page.
      keywords: { GB: ['food traders wanted', 'food truck pitches', 'street food pitches', 'catering pitches'], US: ['food vendors wanted', 'food truck vendors wanted', 'food truck events'] },
      slugs: { GB: 'food-traders-wanted', US: 'food-vendors-wanted', CA: 'food-vendors-wanted', AU: 'food-vendors-wanted', IE: 'food-traders-wanted', NZ: 'food-vendors-wanted', SG: 'food-vendors-wanted', HK: 'food-vendors-wanted' },
      labels: { GB: 'Food traders wanted', US: 'Food vendors & food trucks wanted', CA: 'Food vendors & food trucks wanted', AU: 'Food vendors wanted', IE: 'Food traders wanted', NZ: 'Food vendors wanted', SG: 'Food vendors wanted', HK: 'Food vendors wanted' },
      blurb: 'Street food, catering, food trucks and drinks: events that want food traders.' },
    { key: 'christmas', filters: { types: ['christmas_market', 'holiday_market'] },
      keywords: { GB: ['christmas market stalls', 'christmas market traders wanted', 'christmas market pitches'], US: ['holiday market vendors', 'christmas market vendor applications'] },
      slugs: { GB: 'christmas-market-stalls', US: 'holiday-market-vendors', CA: 'holiday-market-vendors', AU: 'christmas-market-stalls', IE: 'christmas-market-stalls', NZ: 'christmas-market-stalls', SG: 'christmas-market-booths', HK: 'christmas-market-booths' },
      labels: { GB: 'Christmas market stalls', US: 'Holiday market vendors', CA: 'Holiday market vendors', AU: 'Christmas market stalls', IE: 'Christmas market stalls', NZ: 'Christmas market stalls', SG: 'Christmas market booths', HK: 'Christmas market booths' },
      blurb: 'Christmas and holiday markets looking for stallholders for the festive season.' },
    { key: 'markets', filters: { types: ['market'] },
      keywords: { GB: ['market stall opportunities', 'market stallholder applications', 'market pitches'], US: ['farmers market vendors', 'farmers market vendor applications'] },
      slugs: { GB: 'market-stall-opportunities', US: 'farmers-market-vendors', CA: 'farmers-market-vendors', AU: 'market-stalls', IE: 'market-stall-opportunities', NZ: 'market-stalls', SG: 'market-booths', HK: 'market-stalls' },
      labels: { GB: 'Market stall opportunities', US: 'Farmers market vendors', CA: 'Farmers’ market vendors', AU: 'Market stalls', IE: 'Market stall opportunities', NZ: 'Market stalls', SG: 'Market booths', HK: 'Market stalls' },
      blurb: 'Weekly, monthly and farmers’ markets with space for traders.' },
    { key: 'craft', filters: { sells: 'craft' },
      keywords: { GB: ['craft fair stall holders', 'craft fairs looking for stallholders'], US: ['craft fair vendor applications', 'craft show vendors wanted'] },
      slugs: { GB: 'craft-fair-stall-holders', US: 'craft-fair-vendor-applications', CA: 'craft-show-vendor-applications', AU: 'craft-market-stallholders', IE: 'craft-fair-traders', NZ: 'craft-market-stallholders', SG: 'craft-market-vendors', HK: 'craft-market-vendors' },
      labels: { GB: 'Craft fair stall holders', US: 'Craft fair vendor applications', CA: 'Craft show vendor applications', AU: 'Craft market stallholders', IE: 'Craft fair traders', NZ: 'Craft market stallholders', SG: 'Craft market vendors', HK: 'Craft market vendors' },
      blurb: 'Craft fairs, makers’ markets and art trails that want handmade and artisan traders.' },
    { key: 'sports', filters: { types: ['sport'] },
      keywords: { GB: ['race day traders', 'sporting event trade stands'], US: ['stadium vendors', 'sports event vendor applications', 'marathon expo vendors'] },
      slugs: { GB: 'sporting-event-traders', US: 'sports-event-vendors', CA: 'sports-event-vendors', AU: 'sporting-event-stallholders', IE: 'sporting-event-traders', NZ: 'sporting-event-stallholders', SG: 'sports-event-vendors', HK: 'sports-event-vendors' },
      labels: { GB: 'Sporting event & race day traders', US: 'Sports event & stadium vendors', CA: 'Sports event vendors', AU: 'Sporting event stallholders', IE: 'Sporting event traders', NZ: 'Sporting event stallholders', SG: 'Sports event vendors', HK: 'Sports event vendors' },
      blurb: 'Race days, rodeos, marathons, tournaments and stadium concessions.' },
    { key: 'council', filters: { organiser_types: ['council'] }, markets: ['GB'],
      slugs: { GB: 'council-event-trader-applications' }, labels: { GB: 'Council event trader applications' },
      blurb: 'Council-run events, markets and street trading pitches.' },
    { key: 'street-trading', filters: { types: ['street_trading'] }, markets: ['GB'],
      slugs: { GB: 'street-trading-pitches' }, labels: { GB: 'Street trading pitches' },
      blurb: 'Council street trading consents and permanent pitches.' }
  ];

  // Market-specific practical guidance (kept deliberately general: "organisers often ask for…").
  const GUIDANCE = {
    GB: ['public liability insurance (often £5m cover)', 'a food hygiene rating and council food business registration if you sell food', 'gas and electrical safety certificates for catering units', 'photos of your stall or unit'],
    US: ['a vendor or temporary event permit from the city or county', 'a state sales tax permit', 'a health department permit if you sell food', 'general liability insurance and photos of your booth'],
    CA: ['a municipal vendor or event permit', 'public health approval if you sell food', 'liability insurance'],
    AU: ['public liability insurance', 'council food business registration if you sell food', 'photos of your stall'],
    IE: ['public liability insurance', 'HSE/FSAI food registration if you sell food', 'casual trading licence for some public spaces'],
    NZ: ['public liability insurance', 'a food control plan or registration if you sell food', 'photos of your stall'],
    SG: ['event organiser approval and any required SFA food licence for food stalls', 'your business registration (UEN)', 'photos of your booth'],
    HK: ['organiser approval and any required FEHD licence or permit for food', 'your business registration', 'photos of your booth']
  };

  // Legacy PitchList / old FindPitches URLs → new canonical paths (301s at the edge in production).
  const LEGACY = [
    { from: 'pitchlist.uk/', to: '/uk/' },
    { from: 'pitchlist.uk/find-pitches', to: '/uk/find-pitches/' },
    { from: 'pitchlist.uk/database', to: '/uk/find-pitches/' },
    { from: 'pitchlist.uk/stall-holders-wanted', to: '/uk/stall-holders-wanted/' },
    { from: 'pitchlist.uk/festival-trader-applications', to: '/uk/festival-trader-applications/' },
    { from: 'pitchlist.uk/festival-vendors-wanted', to: '/uk/festival-trader-applications/', note: 'merged: same intent' },
    { from: 'pitchlist.uk/food-traders-wanted', to: '/uk/food-traders-wanted/' },
    { from: 'pitchlist.uk/food-truck-pitches', to: '/uk/food-traders-wanted/', note: 'merged: same intent' },
    { from: 'pitchlist.uk/market-stallholder-applications', to: '/uk/market-stall-opportunities/' },
    { from: 'pitchlist.uk/council-event-trader-applications', to: '/uk/council-event-trader-applications/' },
    { from: 'pitchlist.uk/areas/{county}', to: '/uk/{county}/', note: 'slug overrides below; unknown areas → /uk/' },
    { from: 'findpitches.com/uk/', to: '/uk/', note: 'unchanged' },
    { from: 'findpitches.com/us/', to: '/us/', note: 'unchanged' },
    { from: 'findpitches.com/us/find-pitches', to: '/us/find-pitches/', note: 'unchanged' }
  ];
  const AREA_OVERRIDES = { 'greater-london': 'london', 'antrim': 'northern-ireland', 'belfast': 'northern-ireland', 'midlands': 'midlands' };

  // Per-market page policy. SG and HK terminology is provisional (not validated with keyword data), so they get a
  // market hub only: no intent or region landing pages until Chris approves a keyword set. Both remain noindex while building.
  const MARKET_POLICY = {
    SG: { hub_only: true, note: 'Terminology provisional: hub page only until keyword research is done' },
    HK: { hub_only: true, note: 'Terminology provisional: hub page only until keyword research is done' }
  };
  // Regions that are real in the data but aren't genuine, well-defined places for a landing page.
  const NON_INDEXABLE_REGIONS = {
    'gb/midlands': 'Catch-all "Midlands" bucket in the source data. It overlaps East and West Midlands, so it isn’t a genuine area to target'
  };

  FP.seoConfig = {
    // ELIGIBILITY threshold (not the whole indexing decision): a page needs at least this many live listings before the
    // other indexability checks are even considered. Thin-content rule carried over from PitchList's SEO strategy.
    // Change it here only; nothing else hard-codes the number.
    thresholds: { eligibility_min: 3 },
    marketPolicy: MARKET_POLICY,
    nonIndexableRegions: NON_INDEXABLE_REGIONS,
    intents: INTENTS,
    guidance: GUIDANCE,
    legacy: LEGACY,
    areaOverrides: AREA_OVERRIDES,
    intentFor(market, key) { return FP.seoConfig.intentsFor(market).find(x => x.key === key) || null; },
    intentsFor(market) { if ((MARKET_POLICY[market] || {}).hub_only) return []; return INTENTS.filter(i => !i.markets || i.markets.includes(market)); },
    hubOnly(market) { return !!(MARKET_POLICY[market] || {}).hub_only; },
    bySlug(market, slug) { return FP.seoConfig.intentsFor(market).find(i => i.slugs[market] === slug) || null; }
  };
})();

// ---- public/assets/js/seo/seo-core.js
/*
 * FindPitches SEO core (offline draft).
 * Pure functions: path resolution, canonical/redirect rules, metadata, structured data,
 * indexability, internal links and sitemap entries. No DOM, no network. Designed so the same
 * logic can later run in a server/edge renderer against the real customer API.
 */
(function () {
  const FP = (window.FP = window.FP || {});
  const R = FP.routes, CFG = FP.seoConfig;
  const cap = s => s ? s[0].toUpperCase() + s.slice(1) : s;
  const inPlace = name => /^the\s/i.test(name) ? 'the ' + name.slice(4) : name;
  // Regions like 'South East' read as 'the South East' mid-sentence.
  const placeOf = r => r.level === 'region' && /^(North|South|East|West|Yorkshire)/.test(r.name) ? 'the ' + r.name : inPlace(r.name);
  const TYPE_PLURAL = { christmas_market: 'Christmas markets', holiday_market: 'holiday markets', food_festival: 'food festivals', festival: 'festivals', market: 'markets', street_trading: 'street trading pitches', show: 'shows', concession: 'concessions', event: 'events', sport: 'sporting events' };
  const listJoin = a => a.length < 2 ? a.join('') : a.slice(0, -1).join(', ') + ' and ' + a[a.length - 1];
  const clip = (s, n) => s.length <= n ? s : s.slice(0, n - 1).replace(/\s+\S*$/, '') + '…';

  /* ---------------- 1. Path resolution ---------------- */
  // ctx: { markets: [...], regions: { GB: [...regions] , ... } }
  function resolve(input, ctx) {
    let raw = String(input || '/').trim();
    const fromPitchList = /^(https?:\/\/)?(www\.)?\/?pitchlist\.uk/i.test(raw);
    raw = raw.replace(/^(https?:\/\/)?(www\.)?\/?pitchlist\.uk/i, '').replace(/^https?:\/\/[^/]+/i, '');
    if (fromPitchList && !raw.replace(/\//g, '')) return { kind: 'redirect', status: 301, to: '/uk/', reason: 'Legacy PitchList homepage' };
    const legacyHost = /^pitchlist\.uk/i.test(String(input || '')) || /^\/?pitchlist/i.test(raw);
    let path = raw.split(/[?#]/)[0];
    if (!path.startsWith('/')) path = '/' + path;
    const segs = path.split('/').filter(Boolean);
    const norm = '/' + segs.map(s => s.toLowerCase()).join('/') + (segs.length ? '/' : '');

    // Legacy PitchList areas pages: /areas/kent → /uk/kent/
    if (segs[0] && segs[0].toLowerCase() === 'areas' && segs[1]) {
      const s = segs[1].toLowerCase().replace(/\.html$/, ''); const slug = CFG.areaOverrides[s] || s;
      const ok = (ctx.regions.GB || []).some(r => r.slug === slug);
      return { kind: 'redirect', status: 301, to: ok ? `/uk/${slug}/` : '/uk/', reason: 'Legacy PitchList area page' };
    }
    // Legacy PitchList intent pages at the root: /stall-holders-wanted → /uk/stall-holders-wanted/
    if (segs.length === 1 && !R.marketOf(segs[0])) {
      const s = segs[0].toLowerCase().replace(/\.html$/, '');
      const hit = CFG.legacy.find(l => l.from === 'pitchlist.uk/' + s);
      if (hit) return { kind: 'redirect', status: 301, to: hit.to, reason: 'Legacy PitchList page' + (hit.note ? ` (${hit.note})` : '') };
      return { kind: 'not_found', reason: `No page at ${path}` };
    }
    if (!segs.length) return { kind: 'app', to: 'index.html', reason: 'Global homepage' };

    const market = R.marketOf(segs[0]);
    if (!market) return { kind: 'not_found', reason: `Unknown market "${segs[0]}"` };
    // Canonical codes in the URL (/gb/) redirect to the friendly slug (/uk/)
    if (segs[0].toLowerCase() !== R.slugOf(market)) return { kind: 'redirect', status: 301, to: norm.replace(/^\/[^/]+\//, `/${R.slugOf(market)}/`), reason: 'Market slug is the friendly form' };
    if (path !== norm) return { kind: 'redirect', status: 301, to: norm, reason: 'Lowercase + trailing slash canonical form' };

    const regions = ctx.regions[market] || [];
    const regionBy = s => regions.find(r => r.slug === s) || null;
    const a = segs[1] && segs[1].toLowerCase(), b = segs[2] && segs[2].toLowerCase();
    if (segs.length > 3) return { kind: 'not_found', reason: 'Too many path segments' };
    if (!a) return page(market, null, null);
    if (a === 'find-pitches') return { kind: 'app', to: R.draft.finder(market), reason: 'Finder (application page, not an SEO landing page)' };
    if (a === 'opportunity' && b) return { kind: 'app', to: R.draft.opportunity(segs[2]), reason: 'Opportunity page' };
    const ia = CFG.bySlug(market, a), ra = regionBy(a);
    if (!b) {
      if (ia) return page(market, ia, null);
      if (ra && !CFG.hubOnly(market)) return page(market, null, ra);
      return { kind: 'not_found', reason: `Nothing called "${a}" in ${market}` };
    }
    const ib = CFG.bySlug(market, b), rb = regionBy(b);
    if (ia && rb && ia.generic) return { kind: 'redirect', status: 301, to: `/${R.slugOf(market)}/${rb.slug}/`, reason: `"${ia.labels[market]}" in a region is the same page as the region page` };
    if (ia && rb) return page(market, ia, rb);
    if (ra && ib && ib.generic) return { kind: 'redirect', status: 301, to: `/${R.slugOf(market)}/${ra.slug}/`, reason: `"${ib.labels[market]}" in a region is the same page as the region page` };
    if (ra && ib) return { kind: 'redirect', status: 301, to: `/${R.slugOf(market)}/${ib.slugs[market]}/${ra.slug}/`, reason: 'Canonical order is /market/intent/region/' };
    return { kind: 'not_found', reason: `No page for "${a}/${b}"` };

    function page(m, intent, region) {
      const p = `/${R.slugOf(m)}/` + (intent ? intent.slugs[m] + '/' : '') + (region ? region.slug + '/' : '');
      const type = intent && region ? 'combo' : intent ? 'intent' : region ? 'region' : 'market';
      return { kind: 'page', type, market: m, intent, region, path: p, legacyHost };
    }
  }

  /* ---------------- 2. Search filters for a page ---------------- */
  function filters(d) {
    const f = { market: d.market };
    if (d.intent) Object.assign(f, JSON.parse(JSON.stringify(d.intent.filters)));
    if (d.region) f.region = d.region.id;
    return f;
  }
  const pathOf = (m, intent, region) => `/${R.slugOf(m)}/` + (intent ? intent.slugs[m] + '/' : '') + (region ? region.slug + '/' : '');

  /* ---------------- 3. Counts & indexability ---------------- */
  function countFor(inv, intent, region) {
    if (!inv) return 0;
    if (intent && region) return inv.combos[intent.key + '|' + region.id] || 0;
    if (intent) return inv.intents[intent.key] || 0;
    if (region) return inv.regions[region.id] || 0;
    return inv.market_total || 0;
  }
  // Indexability is more than a listing count. A page is indexable only when ALL checks pass:
  //   launch      the market is customer-live (launch_status from the market registry)
  //   eligibility at least thresholds.eligibility_min live listings (configurable, in seo-config.js)
  //   unique      its listings aren't identical to a broader page's (child pages must add something)
  //   relevance   it targets a genuine place/intent (not a catch-all bucket; not blocked by market policy)
  // Pages that fail stay useful to visitors but are noindex,follow, left out of the sitemap, the indexable inventory and
  // automated internal links.
  function assess(market, inv, regById, intent, region) {
    const min = CFG.thresholds.eligibility_min, code = market.code;
    const count = countFor(inv, intent, region); const checks = [];
    const live = market.launch_status === 'live';
    checks.push({ id: 'launch', label: 'Market is live', ok: live, detail: live ? `${market.name} is customer-live` : `${market.name} is ${market.launch_status}: not launched for customers yet` });
    checks.push({ id: 'eligibility', label: `At least ${min} live listings`, ok: count >= min, detail: `${count} live listing${count === 1 ? '' : 's'}${count < min ? ': thin page' : ''}` });
    const bad = CFG.nonIndexableRegions || {};
    const okParent = r => r && !bad[r.id];
    let dup = null;
    if (count > 0) {
      const parent = region && region.parent_id ? regById[region.parent_id] : null;
      if (intent && region) {
        if (count === countFor(inv, null, region)) dup = pathOf(code, null, region);
        else if (okParent(parent) && count === countFor(inv, intent, parent)) dup = pathOf(code, intent, parent);
      } else if (region) { if (okParent(parent) && count === countFor(inv, null, parent)) dup = pathOf(code, null, parent); }
      else if (intent && !intent.generic) { if (count === countFor(inv, null, null)) dup = pathOf(code); }
    }
    checks.push({ id: 'unique', label: 'Adds listings beyond a broader page', ok: !dup, detail: dup ? `Same listings as ${dup}` : count ? 'Distinct set of listings' : 'n/a (no listings)' });
    let rel = null;
    if (region && bad[region.id]) rel = bad[region.id];
    if ((intent || region) && CFG.hubOnly(code)) rel = (CFG.marketPolicy[code] || {}).note || 'Market is hub-only';
    checks.push({ id: 'relevance', label: 'Genuine place and intent', ok: !rel, detail: rel || (region ? `${region.name} (${region.level})` : intent ? intent.labels[code] : 'Market hub') });
    const fail = checks.find(c => !c.ok);
    return { count, eligible: count >= min, indexable: !fail, reason: fail ? fail.detail : 'Passes all checks', checks, duplicate_of: dup };
  }
  const indexability = (d, market, inv, regById) => assess(market, inv, regById || {}, d.intent, d.region);

  /* ---------------- 4. Metadata ---------------- */
  function words(market) { const L = market.vocab.listings || 'Opportunities'; return { noun: L.toLowerCase(), Noun: L }; }
  function seasonYear(search) {
    const ys = {}; (search.results || []).forEach(o => { if (o.dates.start) { const y = o.dates.start.slice(0, 4); ys[y] = (ys[y] || 0) + 1; } });
    const top = Object.entries(ys).sort((a, b) => b[1] - a[1])[0]; return top ? top[0] : null;
  }
  function meta(d, data) {
    const { market, search, inventory, regionPath, today } = data;
    const regById = Object.fromEntries((data.regions || []).map(r => [r.id, r]));
    const visible = data.visible || (search.results || []);
    const w = words(market);
    const place = d.region ? placeOf(d.region) : market.the;
    const label = d.intent ? d.intent.labels[d.market] : null;
    const count = countFor(inventory, d.intent, d.region);
    const ix = indexability(d, market, inventory, regById);
    const h1 = d.type === 'market' ? `${w.Noun} across ${market.the}`
      : d.type === 'region' ? `${w.Noun} in ${place}`
      : `${label} in ${place}`;
    const season = d.intent && ['festivals', 'christmas'].includes(d.intent.key) ? seasonYear(search) : null;
    const hubLong = `${w.Noun}, markets & festivals across ${market.the}`;
    let title = (d.type === 'market' ? ((hubLong + ' | FindPitches').length <= 65 ? hubLong : `${w.Noun} across ${market.the}`)
      : d.type === 'region' ? `${w.Noun} in ${place}: markets, fairs & festivals` : `${label}${season ? ' ' + season : ''} in ${place}`);
    if ((title + ' | FindPitches').length > 65 && d.type === 'region') title = `${w.Noun} in ${place}`;
    title = title + ' | FindPitches';
    const next = (search.results || []).filter(o => o.dates.start && o.dates.start >= today).sort((a, b) => a.dates.start.localeCompare(b.dates.start))[0];
    const fmt = iso => new Intl.DateTimeFormat(market.locale, { day: 'numeric', month: 'short', year: 'numeric', timeZone: 'UTC' }).format(new Date(iso + 'T12:00:00Z'));
    const typesTop = Object.entries((search.facets && search.facets.types) || {}).sort((a, b) => b[1] - a[1]).slice(0, 3).map(([k]) => TYPE_PLURAL[k] || k);
    const description = clip(count
      ? `${d.intent ? label + ' in ' + place + ': ' + count + ' checked listings' : count + ' checked ' + w.noun + ' in ' + place}${typesTop.length ? ', including ' + listJoin(typesTop) : ''}. ${next ? `Next: ${next.title}, ${fmt(next.dates.start)}. ` : ''}Every listing links to the organiser.`
      : `Find ${d.intent ? label.toLowerCase() : w.noun} in ${place} on FindPitches. Checked listings straight from organisers, with alerts when new ones appear.`, 155);

    const canonical = R.abs(d.path);
    // Breadcrumbs follow the URL structure: market › intent › region ancestors › region
    const bc = [{ name: 'FindPitches', path: '/' }, { name: market.name, path: pathOf(d.market) }];
    if (d.intent) bc.push({ name: label, path: pathOf(d.market, d.intent) });
    (regionPath || []).forEach(r => bc.push({ name: r.name, path: pathOf(d.market, d.intent, r) }));

    // hreflang: only for pages that exist as equivalents in other markets (market hubs and market-level intents)
    const hreflang = [];
    if (ix.indexable && (d.type === 'market' || d.type === 'intent')) {
      (data.markets || []).forEach(m => {
        if (m.launch_status !== 'live') return;
        if (d.type === 'intent' && !CFG.intentFor(m.code, d.intent.key)) return;
        const inv = data.inventories && data.inventories[m.code]; if (!inv) return;
        const eq = d.type === 'intent' ? CFG.intentFor(m.code, d.intent.key) : null;
        if (assess(m, inv, {}, eq, null).indexable) hreflang.push({ lang: m.locale, href: R.abs(pathOf(m.code, d.type === 'intent' ? CFG.intentFor(m.code, d.intent.key) : null)) });
      });
      if (hreflang.length) hreflang.push({ lang: 'x-default', href: R.abs('/') });
    }

    const faq = faqs(d, data, { count, place, label, w, next, fmt });
    // Structured data is deliberately conservative (see docs/SEO_SYSTEM.md):
    //  - BreadcrumbList mirrors the visible breadcrumb exactly.
    //  - ItemList lists exactly the listings visible on the page (never the full count, never hidden items).
    //  - No FAQPage on commercial landing pages (the visible FAQ stays). No Event here: events live on opportunity pages.
    const jsonld = [{ '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: bc.map((b, i) => ({ '@type': 'ListItem', position: i + 1, name: b.name, item: R.abs(b.path) })) }];
    if (visible.length) jsonld.push({ '@context': 'https://schema.org', '@type': 'ItemList', name: h1, numberOfItems: visible.length,
      itemListElement: visible.map((o, i) => ({ '@type': 'ListItem', position: i + 1, url: R.abs(R.opportunityPath(o.market, o.id)), name: o.title })) });
    const intro = [];
    if (count) intro.push(`${count} checked ${d.intent ? 'listings' : w.noun} in ${place}${typesTop.length ? ', including ' + listJoin(typesTop) : ''}.${next ? ` The next one starts ${fmt(next.dates.start)}.` : ''}`);
    else intro.push(market.launch_status === 'live' ? `There are no live listings for this search right now.` : `FindPitches is building coverage in ${market.name}. Listings appear here once they’ve been checked.`);
    if (d.intent) intro.push(d.intent.blurb);
    intro.push('Every listing comes from the organiser’s own page and shows when we last checked it. You apply direct: we never take a cut.');
    const keywords = d.intent && d.intent.keywords ? (d.intent.keywords[d.market] || []) : [];
    return { title, description, h1, canonical, robots: ix.indexable ? 'index,follow' : 'noindex,follow', indexable: ix.indexable, eligible: ix.eligible, index_reason: ix.reason, checks: ix.checks, keywords, count, hreflang, breadcrumbs: bc, jsonld, faq, intro, label, place, season, next };
  }

  function faqs(d, data, x) {
    const m = data.market, g = (CFG.guidance[m.code] || []).slice(0, 3);
    const what = d.intent ? x.label.toLowerCase() : x.w.noun;
    const out = [
      { q: `How many ${what} are there in ${x.place}?`, a: x.count ? `FindPitches currently lists ${x.count} checked ${d.intent ? 'listings' : x.w.noun} in ${x.place}. The list updates as organisers open and close applications.` : `There are none live right now. Set an alert and we’ll email you when one is checked.` },
      { q: `How do I apply?`, a: `Each listing links to the organiser’s own application page. Organisers often ask for ${g.length ? g.join(', ') : 'insurance and photos of your stall'}.` },
      { q: `Does FindPitches guarantee me a ${m.vocab.pitch}?`, a: `No. Organisers choose their ${m.vocab.traders_short}. We make sure every listing is real, comes from the organiser, and shows when it was last checked.` }
    ];
    if (x.next) out.splice(1, 0, { q: `When is the next one?`, a: `${x.next.title} starts ${x.fmt(x.next.dates.start)} (${x.next.location.label}).` });
    return out;
  }

  /* ---------------- 5. Internal links ---------------- */
  // Automated internal links point ONLY at indexable pages (full assess(), not just a count).
  function links(d, data) {
    const { inventory: inv, regions, market } = data;
    const out = []; const intents = CFG.intentsFor(d.market);
    const regById = Object.fromEntries(regions.map(r => [r.id, r]));
    const L = (label, intent, region) => { const a = assess(market, inv, regById, intent, region); return a.indexable ? { label, path: pathOf(d.market, intent, region), count: a.count } : null; };
    const pageIntent = d.intent && d.intent.generic ? null : d.intent; // generic intent × region is the region page
    const keep = a => a.filter(Boolean);
    if (d.region) {
      const other = keep(intents.filter(i => !i.generic && (!d.intent || i.key !== d.intent.key)).map(i => L(i.labels[d.market], i, d.region)));
      if (other.length) out.push({ title: `More ways to trade in ${placeOf(d.region)}`, links: other });
      const kids = keep(regions.filter(r => r.parent_id === d.region.id).map(r => L(r.name, pageIntent, r)));
      if (kids.length) out.push({ title: `Areas in ${placeOf(d.region)}`, links: kids.sort((a, b) => a.label.localeCompare(b.label)) });
      if (d.region.parent_id && regById[d.region.parent_id]) { const l = L(regById[d.region.parent_id].name, pageIntent, regById[d.region.parent_id]); if (l) out.push({ title: 'Wider area', links: [l] }); }
      const sib = keep(regions.filter(r => r.id !== d.region.id && r.parent_id === d.region.parent_id).map(r => L(r.name, pageIntent, r))).sort((a, b) => b.count - a.count).slice(0, 12);
      if (sib.length) out.push({ title: d.intent ? `${d.intent.labels[d.market]} nearby` : 'Nearby', links: sib });
    } else {
      if (!d.intent) { const ints = keep(intents.map(i => L(i.labels[d.market], i, null))); if (ints.length) out.push({ title: 'Popular searches', links: ints }); }
      const top = keep(regions.filter(r => r.level !== 'county').map(r => L(r.name, pageIntent, r))).sort((a, b) => a.label.localeCompare(b.label));
      const lv = regions.find(r => r.level !== 'county'); // label from the taxonomy level, not the country
      if (top.length) out.push({ title: lv && lv.level === 'state' ? 'By state' : 'By region', links: top });
      const counties = keep(regions.filter(r => r.level === 'county').map(r => L(r.name, pageIntent, r))).sort((a, b) => a.label.localeCompare(b.label));
      if (counties.length) out.push({ title: 'By county', links: counties });
      if (d.intent) { const ints = keep(intents.filter(i => i.key !== d.intent.key).map(i => L(i.labels[d.market], i, null))); if (ints.length) out.push({ title: 'Related searches', links: ints }); }
    }
    return out;
  }

  /* ---------------- 6. Inventory → page list & sitemap ---------------- */
  // Every page the system can render for a market, with its full indexability assessment.
  function pages(market, inv, regions) {
    const regById = Object.fromEntries(regions.map(r => [r.id, r]));
    const list = []; const add = (type, intent, region, label) => { const a = assess(market, inv, regById, intent, region); list.push({ type, path: pathOf(market.code, intent, region), label, count: a.count, eligible: a.eligible, indexable: a.indexable, reason: a.reason, checks: a.checks, keywords: intent && intent.keywords ? intent.keywords[market.code] || [] : [] }); };
    add('market', null, null, market.name);
    const ints = CFG.intentsFor(market.code);
    ints.forEach(i => add('intent', i, null, i.labels[market.code]));
    if (!CFG.hubOnly(market.code)) regions.filter(r => inv.regions[r.id]).forEach(r => add('region', null, r, r.name));
    ints.filter(i => !i.generic).forEach(i => regions.forEach(r => { if (inv.combos[i.key + '|' + r.id]) add('combo', i, r, `${i.labels[market.code]} · ${r.name}`); }));
    return list;
  }
  function sitemapXml(entries, lastmod) {
    const esc = s => s.replace(/&/g, '&amp;').replace(/</g, '&lt;');
    return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
      entries.map(e => `  <url><loc>${esc(R.abs(e.path))}</loc><lastmod>${lastmod}</lastmod></url>`).join('\n') + `\n</urlset>\n`;
  }

  FP.seo = { placeOf, resolve, filters, meta, links, pages, sitemapXml, pathOf, countFor, indexability, assess };
})();

export const routes = window.FP.routes;
export const seoConfig = window.FP.seoConfig;
export const seo = window.FP.seo;
